name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nix
      run: |
        curl -L https://nixos.org/nix/install | sh
        . /home/runner/.nix-profile/etc/profile.d/nix.sh

    - name: nix-shell Check
      run: |
        . /home/runner/.nix-profile/etc/profile.d/nix.sh

    - name: Run nix-shell
      run: |
        . /home/runner/.nix-profile/etc/profile.d/nix.sh
        nix-shell --run "/start.sh"
