name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nix
      run: |
        curl -L https://nixos.org/nix/install | sh
        . /home/runner/.nix-profile/etc/profile.d/nix.sh

    - name: nix-shell Check
      run: |
        . /home/runner/.nix-profile/etc/profile.d/nix.sh

    - name: Run nix-shell
      run: |
        set +u
        . /home/runner/.nix-profile/etc/profile.d/nix.sh
        set -u
        nix-shell default.nix &

    - name: Wait for the application to start
      run: |
        sleep 5
    
    - name: Check if the application is running
      run: |
        curl -v http://localhost:3000
