name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nix
      run: |
        curl -L https://nixos.org/nix/install | sh

    - name: nix-shell Check
      run: |
        . /home/runner/.nix-profile/etc/profile.d/nix.sh

    - name: nix-shell version
        run: |
          nix-shell --version
        
    - name: Run nix-shell
      run: |
        nix-shell --run "/app/start.sh"
