name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nix
      run: |
        curl -L https://nixos.org/nix/install | sh
        . /home/runner/.nix-profile/etc/profile.d/nix.sh

    - name: Build the project
      run: |
        set +u
        . /home/runner/.nix-profile/etc/profile.d/nix.sh
        set -u
        nix-shell default.nix --run "echo Build completed"

    - name: Deploy to GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
