name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Cachix and Nix
      uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-22.11

    - name: Build the project using Nix
      run: |
        nix-build default.nix

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v4
      with:
        enablement: true
    
    - name: Debug Deployment
      run: ls -la

    - name: Rename Artifact Directory
      run: |
        # Move the result symlink to a regular directory
        mv ./result ./github-pages
        # Resolve the symlink into a regular directory
        cp -r ./github-pages ./github-pages-resolved
        mv ./github-pages-resolved ./github-pages
        # Confirm the contents of the directory
        ls -la ./github-pages

    - name: Upload artifact to GitHub Pages
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./github-pages
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

  # deploy:
  #   environment:
  #     name: github-pages
  #     url: https://NamrathShetty.github.io/Portfolio # Replace with your GitHub Pages URL
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     pages: write
  #     id-token: write

  #   steps:
  #   - name: Download Build Artifact
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: github-pages

  #   - name: Debug Deployment
  #     run: ls -la
           
  #   - name: Ensure Artifact is a Directory
  #     run: |
  #       if [ ! -d "./github-pages" ]; then
  #         mkdir github-pages-extracted
  #         tar -xvf ./github-pages -C github-pages-extracted
  #         mv github-pages-extracted github-pages
  #       fi
  #       ls -la ./github-pages

  #   - name: Debug Deployment
  #     run: |
  #       echo "Contents of github-pages directory:"
  #       cat ./github-pages

  #   - name: Deploy to GitHub Pages
  #     uses: actions/deploy-pages@v4
  #     with: 
  #       debug: true

