name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Cachix and Nix
      uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-22.11

    - name: Build the project using Nix
      run: |
        nix-build default.nix

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v4
      with:
        enablement: true
    
    - name: Debug Deployment
      run: ls -la

    - name: Rename Artifact Directory
      run: |
        mv ./result ./github-pages
        ls -la ./github-pages

    - name: Upload artifact to GitHub Pages
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./github-pages

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: github-pages

    - name: Debug Deployment
      run: ls -la
           chmod +x ./github-pages

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

