name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use nix-shell-action to build
      uses: cachix/nix-shell-action@v16
      with:
        nix_file: default.nix
        run: |
          echo "Build completed"

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact to GitHub Pages
      uses: actions/upload-artifact@v2
      with:
        name: github-pages
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
